name: Deploy PWA to Scaleway Production

on:
  push:
    branches:
      - ci-cd/scaleway
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Scaleway Container Registry
        uses: docker/login-action@v3
        with:
          username: nologin
          password: ${{ secrets.SCALEWAY_API_KEY }}
          registry: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}
      - name: Build the Docker image
        run: docker buildx build . -t ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/molluscan-pwa \
          --build-arg NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=XXX \
          --build-arg NEXT_PUBLIC_WEATHER_API_KEY=XXX \
          --build-arg SUPABASE_URL=XXX \
          --build-arg SUPABASE_ANON_KEY=XXX
      - name: Push the Docker Image
        run: docker push ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/molluscan-pwa
